# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  run-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    # Add steps to the job
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit --project=chromium
      - store_artifacts:
          path: results.xml
          destination: circleci-docs

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test
